service: employment-portal-api
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  environment:
    EMPLOYEE_TABLE: ${self:custom.employeeTable}
custom:
  employeeTable: experienceInfo-${self:provider.stage}
plugins:
  - serverless-iam-roles-per-function
functions:
  employeePortal:
    handler: api.employeePortal
    name: create-api
    memorySize: 128
    timeout: 5
    events:
      - http:
          method: POST
          path: saveExperienceInfo
          cors: true
      - http:
          method: PUT
          path: updateExperienceInfo
          cors: true
      - http:
          method: GET
          path: getEmployeeExperienceInfo/{employeeId}
          cors: true
      - http:
          method: GET
          path: getAllEmployeesExperienceInfo
          cors: true
resources:
  Resources:
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.employeeTable}
        AttributeDefinitions:
          - AttributeName: EmpId
            AttributeType: S
        KeySchema:
          - AttributeName: EmpId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
