service: employment-portal-api
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    EMPLOYEE_TABLE: ${self:service}-EmployeeTable

functions:
  registerEmployee:
    handler: employee.register
    events:
      - http:
          method: post
          path: register
          cors: true
  signInEmployee:
    handler: employee.signIn
    events:
      - http:
          method: post
          path: signIn
          cors: true
resources:
  Resources:
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: employeeTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
          # - AttributeName: someOtherAttribute
          #   AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
