name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Serverless Framework
        run: npm install -g serverless

      # 👇 This step is critical
      - name: Force npm to public registry
        run: |
          npm config delete registry || true
          npm config set registry https://registry.npmjs.org/
          npm config list
      
      - name: Debug npm registry source
        run: |
          npm config list
          cat ~/.npmrc || echo "No user .npmrc"
          cat /etc/npmrc || echo "No system .npmrc"

      - name: Install dependencies
        run: npm install

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: sls deploy --stage dev
